name: push changes on main branch
on:
  push:
    branches:
      - main

jobs:
  my_custom_job_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

    
      - name: testing secret
        run: echo ${{secrets.TOKEN_SECRET}}

      - name: Use a secret
        run: echo ${{ secrets.TOKEN_SECRET }}
      env:
        TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}